### ISSUE TITLE
PosgreSQL Compatibility Tasks

### ISSUE THREAD

**Issue by eliotsykes** [mhgoldman/course_manager#58]
Outstanding (to be done on separate branches):

- [x] Courses List Feature Spec that exercises column sorts, see PR #57 
- [x] Check all list index views columns are sorted and tested in postgres
  - [x] Users index columns test + fixes see PR #59
  - [x] Logs/Audit index columns see PR #60
- ~~_nice to have_ Single database.yml file, see~~
  - https://matthew.mceachen.us/blog/how-to-test-your-rails-application-with-travis-ci-on-different-databases-engines-1220.html
  - http://www.rubytutorial.io/travis-ci-multiple-database/
  - https://gist.github.com/mceachen/2340726
- [x] **See PR #62** Support getting started easily without postgresql. Gemfile.lock/Gemfile bundle install will cause problems. (.pg-enabled gitignored file perhaps and/or multiple Gemfile.lock files?) See
  - https://github.com/thoughtbot/appraisal#readme
  - https://docs.travis-ci.com/user/customizing-the-build/ (search for gemfile / gemfiles in-page)
  - https://github.com/plataformatec/devise/tree/master/gemfiles
  - or simplest solution might be to just have new developers do `bundle --without production` or similar
